name: 'Slack Notification'
description: 'Send a notification to Slack'
inputs:
  select_input:
    description: 'Select an option'
    required: true
    type: string
  string_input:
    description: 'Enter a string'
    required: true
    type: string
  branch_input:
    description: 'Select a branch'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Send notification to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "GitHub Actions Notification",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow executed by:* ${{ github.actor }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Select Input:*\n${{ inputs.select_input }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*String Input:*\n${{ inputs.string_input }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch Input:*\n${{ inputs.branch_input }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Action URL:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Action>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
