name: PR Checklist Validator
description: マージ前にPRセクション内のすべてのチェックリスト項目が完了していることを確認します。
inputs:
  github_token:
    description: 'GitHubトークン'
    required: true
runs:
  using: "composite"
  steps:
    - name: 特定のセクション内のPRチェックリストを確認
      shell: bash
      run: |
        echo "PR本文を取得中..."
        BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)
        echo -e "PR本文:\n$BODY"
        
        # 指定されたタグ内のチェックリストを抽出
        CHECKLIST_SECTION=$(echo "$BODY" | awk '/<!-- PR-CHECKLIST-VALIDATOR:START -->/,/<!-- PR-CHECKLIST-VALIDATOR:END -->/')
        
        echo -e "チェックリストセクション:\n$CHECKLIST_SECTION"
        
        # セクション内の未チェックのチェックリスト項目を見つける正規表現
        UNCHECKED_ITEMS=$(echo "$CHECKLIST_SECTION" | grep -E '\[ \]' | grep -v '^$')
        
        # デバッグ用にUNCHECKED_ITEMSの内容を出力
        echo -e "未チェックの項目:\n$UNCHECKED_ITEMS"
        
        if [ -n "$UNCHECKED_ITEMS" ]; then
          echo "❌ チェックリストに未チェックの項目があります:"
          echo "$UNCHECKED_ITEMS"
          echo "::error::このPRをマージする前に、指定されたセクション内のすべてのチェックリスト項目をチェックする必要があります。"
          exit 1  # 未チェックの項目がある場合、チェックを失敗させる
        else
          echo "✅ 指定されたセクション内のすべてのチェックリスト項目がチェックされています。"
          exit 0  # すべての項目がチェックされている場合、正常終了
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
