name: Hello World Workflow

on:
  push:
    # branches:
    #   - main
    # 全てのブランチを無視することで発火しないようにする
    branches-ignore:
      - '**' 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, World!"
