name: manual workflow

on:
  workflow_dispatch:
    inputs:
      select_input:
        description: 'Select an option'
        required: true
        type: choice
        options:
          - hoge
          - fuga
          - piyo
      string_input:
        description: 'Enter a string'
        required: true
        type: string
      branch_input:
        description: 'Select a branch'
        required: true
        type: choice
        options:
          - main
          - develop
          - feature-branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, World!"

    - name: Send notification to Slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": '*Workflow executed by:* ${{ github.actor }}'+
                    '*Select Input:* ${{ github.event.inputs.select_input }}'+
                    '*String Input:* ${{ github.event.inputs.string_input }}'+
                    '*Branch Input:* ${{ github.event.inputs.branch_input }}'+
                    '*Action URL:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
