name: manual workflow

on:
  workflow_dispatch:
    inputs:
      select_input:
        description: 'Select an option'
        required: true
        type: choice
        options:
          - hoge
          - fuga
          - piyo
      string_input:
        description: 'Enter a string'
        required: true
        type: string
      branch_input:
        description: 'Select a branch'
        required: true
        type: choice
        options:
          - main
          - develop
          - feature-branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, World!"

    - name: Send notification to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "GitHub Actions Notification",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow executed by:* ${{ github.actor }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Select Input:*\n${{ github.event.inputs.select_input }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*String Input:*\n${{ github.event.inputs.string_input }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch Input:*\n${{ github.event.inputs.branch_input }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Action URL:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Action>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
